services:
  go-mail-webhook-service:
    build: .
    image: go-mail-webhook-service
    volumes:
      - "./dev/config/:/go/config" # Place your runtime app config at ./config/config.yaml; see dev/config.example.yaml for an example
