apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: go-mail-webhook-service-cluster
kubeAPI:
  # Explicitly set hostIP/hostPort for Windows to ensure kubectl connectivity
  hostIP: "127.0.0.1"
  hostPort: "6550"
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"