apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-mail-webhook-service.fullname" . }}-config
  labels:
    {{- include "go-mail-webhook-service.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- $cfg := dict -}}
    {{- $_ := set $cfg "logLevel" .Values.logLevel -}}
    {{- $_ := set $cfg "mailSelectors" .Values.mailSelectors -}}
    {{- $_ := set $cfg "callback" .Values.callback -}}
    {{- $_ := set $cfg "mailClient" .Values.mailClient -}}
    {{- toYaml $cfg | nindent 4 }}
