apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-mail-webhook-service.fullname" . }}-config
  labels:
    {{- include "go-mail-webhook-service.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.configs | nindent 4 }}