{{- if and (eq .Values.mailClient.type "gmail") .Values.mailClient.gmail.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.mailClient.gmail.secret.name }}{{ .Values.mailClient.gmail.secret.name }}{{ else }}{{ include "go-mail-webhook-service.fullname" . }}-mail-credentials{{ end }}
  labels:
    {{- include "go-mail-webhook-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 content of Gmail OAuth client credentials file
  {{ .Values.mailClient.gmail.secret.filename | default "client_secret.json" }}: {{ .Values.mailClient.gmail.secret.credentialsBase64 | quote }}
  {{- if .Values.mailClient.gmail.secret.tokenBase64 }}
  # Base64 content of Gmail OAuth token file
  {{ .Values.mailClient.gmail.secret.tokenFilename | default "request.token" }}: {{ .Values.mailClient.gmail.secret.tokenBase64 | quote }}
  {{- end }}
{{- end }}
