{{- if .Values.mailClientCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.mailClientCredentials.name }}{{ .Values.mailClientCredentials.name }}{{ else }}{{ include "go-mail-webhook-service.fullname" . }}-mail-credentials{{ end }}
  labels:
    {{- include "go-mail-webhook-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 content of credentials file provided via .Values.mailClientCredentials.credentialsBase64
  {{ .Values.mailClientCredentials.filename | default "client_secret.json" }}: {{ .Values.mailClientCredentials.credentialsBase64 | quote }}
{{- end }}