{{- if and .Values.mailClient.gmail.enabled .Values.mailClient.gmail.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.mailClient.gmail.secrets.name }}{{ .Values.mailClient.gmail.secrets.name }}{{ else }}{{ include "go-mail-webhook-service.fullname" . }}-mail-credentials{{ end }}
  labels:
    {{- include "go-mail-webhook-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 content of Gmail OAuth client credentials file
  {{ .Values.mailClient.gmail.secrets.filename | default "client_secret.json" }}: {{ .Values.mailClient.gmail.secrets.credentialsBase64 | quote }}
  {{- if .Values.mailClient.gmail.secrets.tokenBase64 }}
  # Base64 content of Gmail OAuth token file
  {{ .Values.mailClient.gmail.secrets.tokenFilename | default "request.token" }}: {{ .Values.mailClient.gmail.secrets.tokenBase64 | quote }}
  {{- end }}
{{- end }}
