{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-mail-webhook-service.serviceAccountName" . }}
  labels:
    {{- include "go-mail-webhook-service.labels" . | nindent 4 }}
{{- end -}}