apiVersion: v2
name: go-mail-webhook-service
description: A Helm chart for deploying go-mail-webhook-service (polls mail and triggers webhooks)
type: application
version: 5.1.0
appVersion: "3.1.0"
home: https://github.com/jo-hoe/go-mail-webhook-service
sources:
  - https://github.com/jo-hoe/go-mail-webhook-service
keywords:
  - mail
  - webhook
  - kubernetes